# Generated by Django 4.0.4 on 2022-05-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='menu_imagens')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ManyToManyField(related_name='item', to='clientes.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=7)),
                ('itens', models.ManyToManyField(blank=True, related_name='pedido', to='clientes.menuitem')),
            ],
        ),
    ]
