# Generated by Django 4.0.4 on 2022-05-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_pedido_cep_pedido_cidade_pedido_estado_pedido_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
