# Generated by Django 4.0.4 on 2022-05-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_pedido_ja_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='ja_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
